name: WorldGuardRegionProtect
author: RitaSister
authors:
  - IRedTea
version: ${internalVersion}
main: net.ritasister.wgrp.WGRPBukkitPlugin
softdepend: [ WorldGuard ]
description: Protect your region on the server.
website: 'https://github.com/RSTeamCore/WorldGuardRegionProtect'
api-version: 1.18
load: STARTUP
commands:
  worldguardregionprotect:
   aliases: [wgrp]