name: ${name}
version: ${version}
author: ${author}
contributor: ${contributor}
main: ${group}.wgrp.WorldGuardRegionProtectPaperBase
depend: [ WorldGuard ]
softdepend: [ PlaceholderAPI ]
description: ${description}
website: https://github.com/RSTeamCore/WorldGuardRegionProtect
api-version: "1.20"
folia-supported: true
load: STARTUP
libraries:
    - net.kyori:adventure-text-minimessage:4.17.0
    - net.kyori:adventure-platform-bukkit:4.3.2

permissions:
    wgrp.admin:
        description: All permissions of this plugin
        default: false
        children:
            - wgrp.command.wgrpbase
            - wgrp.command.reload
            - wgrp.regionprotect
            - wgrp.notify.admin
            - wgrp.command.addregion
            - wgrp.command.removeregion
    wgrp.*:
        description: Alias for wgrp.admin
        default: false
    wgrp.command.wgrpbase:
        description: Access for /wgrp command
    wgrp.command.addregion:
        description: Access for /wgrp addregion
        default: false
    wgrp.command.removeregion:
        description: Access for /wgrp removeregion
        default: false
    wgrp.command.reload:
        description: Access for /wgrp reload command
        default: false
    wgrp.regionprotect:
        description: Bypass region protect
        default: false
    wgrp.notify.admin:
        description: See notifies for admins
        default: false

commands:
    wgregionprotect:
        aliases: [wgrp]
        description: "WGRP Command - main command of WGRP plugin."
